package com.kirenpaul.foregroundservice;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

import java.util.Map;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Base specification class for ForegroundService TurboModule
 *
 * This class defines the contract for the native module implementation.
 * In a production TurboModule, this would be auto-generated by React Native's codegen
 * from the TypeScript spec file (NativeForegroundService.ts).
 *
 * For now, we provide a manual implementation that matches the spec.
 */
public abstract class NativeForegroundServiceSpec extends ReactContextBaseJavaModule implements TurboModule {

    public NativeForegroundServiceSpec(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Nonnull
    @Override
    public abstract String getName();

    /**
     * Get module constants
     *
     * @return Map of constant values
     */
    @Nullable
    public abstract Map<String, Object> getConstants();

    /**
     * Start the foreground service
     *
     * @param config Notification configuration
     * @param promise Promise to resolve/reject
     */
    @ReactMethod
    public abstract void startService(ReadableMap config, Promise promise);

    /**
     * Stop the foreground service
     *
     * @param promise Promise to resolve/reject
     */
    @ReactMethod
    public abstract void stopService(Promise promise);

    /**
     * Force stop the foreground service
     *
     * @param promise Promise to resolve/reject
     */
    @ReactMethod
    public abstract void stopServiceAll(Promise promise);

    /**
     * Update notification of running service
     *
     * @param config Updated notification configuration
     * @param promise Promise to resolve/reject
     */
    @ReactMethod
    public abstract void updateNotification(ReadableMap config, Promise promise);

    /**
     * Check if service is running
     *
     * @param promise Promise that resolves to running counter
     */
    @ReactMethod
    public abstract void isRunning(Promise promise);

    /**
     * Run a headless task
     *
     * @param config Task configuration
     * @param promise Promise to resolve/reject
     */
    @ReactMethod
    public abstract void runTask(ReadableMap config, Promise promise);

    /**
     * Cancel a notification by ID
     *
     * @param id Notification ID
     * @param promise Promise to resolve/reject
     */
    @ReactMethod
    public abstract void cancelNotification(double id, Promise promise);

    /**
     * Check POST_NOTIFICATIONS permission (Android 13+)
     *
     * @param promise Promise that resolves to boolean
     */
    @ReactMethod
    public abstract void checkPostNotificationsPermission(Promise promise);
}
